EXERCISE_ALIASES = {
    "bench": "Bench Press",
    "bench press": "Bench Press",
    "bp": "Bench Press",
    "incline": "Incline Bench Press",
    "incline bench": "Incline Bench Press",
    "incline db": "Incline Dumbbell Press",
    "ohp": "Overhead Press",
    "overhead press": "Overhead Press",
    "military press": "Overhead Press",
    "squat": "Back Squat",
    "back squat": "Back Squat",
    "rdl": "Romanian Deadlift",
    "rdls": "Romanian Deadlift",
    "romanian deadlift": "Romanian Deadlift",
    "deadlift": "Deadlift",
    "dl": "Deadlift",
    "pullup": "Pull-Up",
    "pull-up": "Pull-Up",
    "pull up": "Pull-Up",
    "pulldown": "Lat Pulldown",
    "lat pulldown": "Lat Pulldown",
    "lat pulldowns": "Lat Pulldowns",
    "row": "Barbell Rows",
    "barbell row": "Barbell Rows",
    "barbell rows": "Barbell Rows",
    "bb row": "Barbell Rows",
    "cable row": "Cable Row",
    "cable rows": "Cable Rows",
    "seated cable row": "Seated Cable Rows",
    "seated cable rows": "Seated Cable Rows",
    "lateral raise": "Lateral Raise",
    "laterals": "Lateral Raise",
    "lat raise": "Lateral Raise",
    "curl": "Barbell Curl",
    "bicep curl": "Dumbbell Curl",
    "hammer curl": "Hammer Curl",
    "tricep pushdown": "Tricep Pushdown",
    "tricep pushdowns": "Tricep Pushdown",
    "pushdown": "Tricep Pushdown",
    "skull crusher": "Skull Crusher",
    "dip": "Tricep Dip",
    "face pull": "Face Pull",
    "face pulls": "Face Pull",
    "leg press": "Leg Press",
    "lunge": "Lunge",
    "lunges": "Lunge",
    "leg curl": "Leg Curl",
    "leg curls": "Leg Curl",
    "leg extension": "Leg Extension",
    "leg extensions": "Leg Extension",
    "calf raise": "Calf Raise",
    "calf raises": "Calf Raise",
    "plank": "Plank",
    "crunch": "Crunch",
}


def normalize_exercise_name(name: str) -> str:
    cleaned = str(name or "").lower().strip()
    if cleaned in EXERCISE_ALIASES:
        return EXERCISE_ALIASES[cleaned]
    return str(name or "").strip().title()
